version: '3'
services:
  pubsub:
    image: "ubcece/oneos-ready:20.01"
    ports:
    - 1883:1883
    command: bash -c "oneos psd"

  mongo:
    image: "ubcece/oneos-ready:20.01"
    ports:
    - 27018:27017
    command: bash -c "mongod --bind_ip ::,0.0.0.0"

  oneosd-1:
    image: "ubcece/oneos-ready:20.01"
    ports:
    - 3001:3000
    - 5001:5000
    command: bash -c "sleep 2s && oneosd runtime-1"

  oneosd-2:
    image: "ubcece/oneos-ready:20.01"
    ports:
    - 3002:3000
    - 5002:5000
    command: bash -c "sleep 2s && oneosd runtime-2"

  oneosd-3:
    image: "ubcece/oneos-ready:20.01"
    ports:
    - 3003:3000
    - 5003:5000
    command: bash -c "sleep 2s && oneosd runtime-3"

